specVersion: 1.0.0
name: SubQuery Dictionary - Polymesh
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  A SubQuery Dictionary Project that provides increased indexing speed for Polymesh chains
repository: 'https://github.com/subquery/subql-dictionary'
schema:
  file: ./schema.graphql
network:
  chainId: '0x2ace05e703aa50b48c0ccccfc8b424f7aab9a1e2c424ed12e45d20b1e8ffd0d6'
  endpoint: 'wss://testnet-rpc.polymesh.live'
  chaintypes:
    file: ./dist/chainTypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
